### PR TITLE
feat(service): Add AWS SNS

### PR DESCRIPTION
**Pull request by raphaelabrantes**
As promised, same as issue #102 but with the errors fixed.
Cheers,
:kiwi_fruit:

### CODE REVIEW

**Comment by nikoksr** [comment]
Hey @raphaelabrantes, first of all I want to thank you for your amazing contribution and for taking the time to re-push your changes over a dev branch. 

Everything looks really good, I just noticed that your using [stretchr/testify/mock](https://github.com/stretchr/testify/mock) for mocking and testing your service. So far, at the time of writing this the handful of services that are tested are using [vektra/mockery](https://github.com/vektra/mockery) for mocking and testing. If you know of any advantages to your approach compared to *mockery*, I would really love to know them. I would like to add tests for all other services soon as well and by that time, we should of course have agreed on a central mocking framework. I would just like to know your opinion!

**Comment by raphaelabrantes** [comment]
Hey @nikoksr, that I'm aware of, there is no real big advantages or disadvantages for both of them, but I have no deep knowledge about this.  I used testify because my monkey brain didn't notice your usage of mockery, so I apologize.
If you want I can change it to mockery, just let me know.
Cheers,
:kiwi_fruit:

**Comment by nikoksr** [comment]
Hey @raphaelabrantes, so sorry for the late reply! 

I'd love to keep our mocks consistent of course, so if you feel like rewriting that, I'd really appreciate it!

Best regards.

**Comment by nikoksr** [comment]
@raphaelabrantes ping

**Comment by raphaelabrantes** [comment]
Hello @nikoksr 
I wont be able to finish this for a while, feel free to close this pull request.
Sorry for the inconvenience.

**Comment by nikoksr** [comment]
@raphaelabrantes No problem! On second thought, I'm leaning towards merging it anyway. 

Most services still need tests and I'm working sporadically to change that, so I think it would only be an advantage for notify if we merged your service because it would be basically the same amount of work to write new tests from scratch for your service or replace the existing ones. 

What do you think? Would you be okay with me merging your PR and then overwriting your tests completely soon?

**Comment by raphaelabrantes** [comment]
@nikoksr Sure, no problem, I am actually happy to hear that :laughing:

**Pull request merged**
