### PR TITLE
build: add build helpers and basic CI

### PR DESCRIPTION
**Pull request by nikoksr**
## Info

Adding some build helpers like _Makefile_ and some very basic CI tools, like a _build workflow_, _kodiak_, _wip_ and _semver_ bot configs.

## Proposed changes

- Add [dependabot](https://github.com/marketplace/dependabot-preview) config
- Add [kodiak](https://github.com/chdsbd/kodiak) config
- Add _GitHub action_ for testing and linting any PRs
- Add a _Makefile_ 
- Add _go-generate_ directives to [notify.go](https://github.com/nikoksr/notify/notify.go)
- Update [contribution guidelines](https://github.com/nikoksr/notify/CONTRIBUTING.md)

## Note

_Dependabot_ will mark PRs that are related to dependencies with the label `automerge` which should trigger _Kodiak_ to automatically merge the updated dependencies.

### CODE REVIEW

**Comment by nikoksr** [comment]
@j-wil could you take a quick look and give me feedback if you agree with the changes and additions?

**Comment by j-wil** [comment]
@nikoksr  I'll take a look at this tonight

**Comment by nikoksr** [comment]
hey @j-wil, just wanted to check back to see if you agree with the changes.

**Comment by j-wil** [comment]
@nikoksr  Sorry we landed a couple of new projects at work so I've been underwater. I think everything looks pretty good here

**Comment by nikoksr** [comment]
@j-wil hey man, no worries! Hope things go well and thanks for the review.

**Pull request merged**
