### PR TITLE
Add plaintext toggle

### PR DESCRIPTION
**Pull request by janboll**
## Description
Adding a toggle, that makes it possible to send E-Mails as unformatted Plain text.

## Motivation and Context
I want to send E-Mails as unformatted Plain Text. Right now the mail service sends out e-mails as HTML only. 

## How Has This Been Tested?

- Tested locally using implementation. 
- Added some tests to ensure fields are set correctly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by janboll** [comment]
Hi, @nikoksr, @svaloumas, is there anything I can do to get this PR merged?

**Comment by nikoksr** [comment]
Hi @janboll, sorry for the delay! We're both rather caught up atm. I'll throw a look at it later today tho, would that help you out? We greatly appreciate your contribution!

**Comment by janboll** [comment]
Of course, thank you for the feedback!

**Comment by nikoksr** [comment]
Hi @janboll, looking at your PR, everything looks very good! We appreciate it.

The only thing that came to my mind is the maintainability of your solution. A solution I would personally like better would be if instead of using fixed text formats, which require functions, like `func (m Mail) UsePlainTextBody() { ... }`, we rather use the text formats as parameters to a function like `func (m Mail) UseTextFormat(format string) { ... }` and continue working with it internally. 

The advantage would be that we can repeat the same pattern for other services and not use n functions in the style `UseXXXTextBody() { ... }`. What if we need to support `HTML`, `JSON`, `XML`, `Text` etc? I am sure you get my point. 

Please let me know what you think and if you have a better suggestion, so that we can get this merged asap!

cc @svaloumas adding you in case you have any additions to this.

**Comment by janboll** [comment]
That makes sense. I'll refactor the PR!

**Comment by janboll** [comment]
I refactored the change a little to use a single function to set the correct body format settings (With the naming of the method I sicked to E-Mail terminology). 

I am unsure if the solution I proposed meets your expectations. Cause reading your comment again, did you think about changing the Notifier interface and adding methods to format the message?

**Review by nikoksr — APPROVED** [review]

**Comment by nikoksr** [comment]
@janboll appreciate the quick fix! No, you did absolutely the right thing, no worries there! I don't want it to be part of the `Notifier` interface since this behavior should stay service specific imo. 

 I'll fix the linter issues for you real quick and then we're ready to merge! Thank you so much for your time and efforts.

**Comment by nikoksr** [comment]
Ignoring codecov complaining here. Yes, send method should be tested but since the `mail` package was untested prior to your PR and you've only added funcitonality and did not implement the whole service, I don't expect you to write tests for the whole service and see this as an overall improvement nonetheless.

**Review by nikoksr — APPROVED** [review]

**Pull request merged**
