### PR TITLE
feat(service): Add Web Push

### LINKED ISSUE #112: feat(service): Add Web Push service
**Is your feature request related to a problem? Please describe.**

Missing support for [Web Push Notifications](https://developers.google.com/web/fundamentals/push-notifications).

**Describe the solution you'd like**

Implement a [notification service](https://github.com/nikoksr/notify/tree/main/service) and use existing services such as [WhatsApp](https://github.com/nikoksr/notify/tree/main/service/whatsapp) as a guide for implementation. At the time writing this, [SherClockHolmes/webpush-go](https://github.com/SherClockHolmes/webpush-go) seems to be the best client library for our service.

### PR DESCRIPTION
**Pull request by KaviiSuri**
## Description
This introduces the web push service as a notifier in the library. It uses [webpush-go](https://github.com/SherClockHolmes/webpush-go/) to handle the notifications.

This PR is still a draft!

## Motivation and Context
This PR aims to close #112 

## How Has This Been Tested?
I need some advice on this as the `webpush-go` package does not provide a client struct that we can mock, rather it's a bunch of global functions.

Should the testing be done by creating such an abstraction (client struct)? Or, testing the logic to parse the options from context and payload should be enough?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by KaviiSuri** [comment]
@nikoksr I've implemented the basic webpush notification service in this PR, but I need advice on the testing approach. 
Would love some feedback from too!

**Comment by nikoksr** [comment]
@KaviiSuri thank you so much for this! Looks very promising already. Please excuse the delay, we're both rather busy atm but will come back to this asap!

**Comment by nikoksr** [comment]
Hi @KaviiSuri, so sorry for the big delay. Your PR is next in line, I'll tackle it over the holidays! Once again, appreciate your efforts and patience.

**Comment by KaviiSuri** [comment]
@nikoksr no problem at all! I completed understand.

I hope to contribute and learn more!

**Comment by nikoksr** [comment]
@KaviiSuri going over this now! I'll hit you up with feedback asap. Appreciate your patience so much. Hope things are well with you.

**Comment by gedw99** [comment]
@KaviiSuri 

it’s blocked on static analysis ?

**Comment by KaviiSuri** [comment]
Hey @gedw99 
I just noticed it, it's asking for a package comment, will do it asap!

**Comment by gedw99** [comment]
> asap

ok thanks !

**Comment by KaviiSuri** [comment]
Hey @gedw99, the codacy url shows `503 Service Temporarily Unavailable`. Any idea on how to fix it?

**Comment by gedw99** [comment]
> Hey @gedw99, the codacy url shows `503 Service Temporarily Unavailable`. Any idea on how to fix it?

No
I looked at the Workflows buy nothing stands out .

is their service down ?

**Comment by KaviiSuri** [comment]
> is their service down?
It was, not anymore apparently

**Comment by nikoksr** [comment]
@KaviiSuri finally got to give this my full attention.. so sorry for the huge delay. To compensate you for your patience, you don't need to do any refactoring work, it's all done.

Your struggles with this PR are absolultely understandable to me. And I agree with you, it's not our obligation to test the webpush library in it's fullness. We just have to make sure that whatever data we touch, manipulate and forward to the library is well tested. I've utilized the [httptest.Server](https://pkg.go.dev/net/http/httptest#Server) for this, similar as with our internal [HTTP service](https://github.com/nikoksr/notify/blob/main/service/http/http_test.go). I'm curious for your feedback on this!

Also, I made some changes to your implementation that generalize its usage a bit, but overall it was a joy working with your code. Great job, we appreciate it a ton! I'll go ahead fix the remaining linter issues and we'll be ready to merge right after. Hope you're doing well and sorry again for the delay.

**Comment by KaviiSuri** [comment]
@nikoksr thanks for making the improvements! So happy to contribute to the project, would love to do more work here moving forward!

**Comment by gedw99** [comment]
MIght be useful to add the following to README 

https://caniuse.com/notifications

IOS needs A2HS. Like ths golang pwa does: https://go-app.dev/

**Comment by nikoksr** [comment]
@KaviiSuri @gedw99 does any of you happen to know an easy way for us to test this solution end-to-end? It's pretty safe to assume that [SherClockHolmes/webpush-go](https://github.com/SherClockHolmes/webpush-go/) does its job well and just works, but I don't like the idea of just releasing the solution without checking its behavior once.

@gedw99 great idea, we'll definitely include this!

**Comment by gedw99** [comment]
> @KaviiSuri @gedw99 does any of you happen to know an easy way for us to test this solution end-to-end? It's pretty safe to assume that [SherClockHolmes/webpush-go](https://github.com/SherClockHolmes/webpush-go/) does its job well and just works, but I don't like the idea of just releasing the solution without checking its behavior once.
> 
> @gedw99 great idea, we'll definitely include this!

I test E2E locally using Caddy, MakeCert for the Server. Gives you a https locally with custom domain name.
https://github.com/FiloSottile/mkcert

For the Wasm services worker i use go.app: https://github.com/maxence-charriere/go-app

I think it would be a good idea to make a little demo in this repo one day when there is time.

In CI, I can run caddy and mkcert, using a makefile as part of github workflows.
It's the exact same makefile used on your laptop, just called as part of CI.
I like this because i get full control and don't need any docker containers in CI so its fast.

For CI of the GUI, thats hard. I use screen shots and Goldens. Its brutal but works. I don't have a framework yet i can recommend because i use GIO which has build in screen shotting.  It runs on web, desktop and mobile. SO its makes cross devcie testing easier. BUT gio is not used by others.

But the idea is to deploy the web app as a github page as part of CI, then you can tell it to screenshot and then you can test you got the right screen shot against your golden screenshot.

Because the makefiles are 100% OS independent you can test for all Desktops and their browsers.

Again i tres that CI browser testing is HARD and these are only suggestions.

I would be happy to work on this with someone.

**Comment by nikoksr** [comment]
> > @KaviiSuri @gedw99 does any of you happen to know an easy way for us to test this solution end-to-end? It's pretty safe to assume that [SherClockHolmes/webpush-go](https://github.com/SherClockHolmes/webpush-go/) does its job well and just works, but I don't like the idea of just releasing the solution without checking its behavior once.
> > @gedw99 great idea, we'll definitely include this!
> 
> I test E2E locally using Caddy, MkCert for the Server. Gives you a https locally with custom domain name. [FiloSottile/mkcert](https://github.com/FiloSottile/mkcert)
> 
> For the Wasm services worker i use go.app: [maxence-charriere/go-app](https://github.com/maxence-charriere/go-app)
> 
> I think it would be a good idea to make a little demo in this repo one day when there is time.
> 
> In CI, I can run caddy and mkcert, using a makefile as part of github workflows. It's the exact same makefile used on your laptop, just called as part of CI. I like this because i get full control and don't need any docker containers in CI so its fast.
> 
> For CI of the GUI, thats hard. I use screen shots and Goldens. Its brutal but works. I don't have a framework yet i can recommend because i use GIO which has build in screen shotting. It runs on web, desktop and mobile. SO its makes cross devcie testing easier. BUT gio is not used by others.
> 
> But the idea is to deploy the web app as a github page as part of CI, then you can tell it to screenshot and then you can test you got the right screen shot against your golden screenshot.
> 
> Because the makefiles are 100% OS independent you can test for all Desktops and their browsers.
> 
> Again i tres that CI browser testing is HARD and these are only suggestions.
> 
> I would be happy to work on this with someone.

Wow, fascinating! Thanks for sharing all that knowledge with us. I wasn't aware of screenshot based browser testing and thus neither of golden.

I wonder how or if we could reduce the complexity of this. [Here's](https://github.com/GoogleChromeLabs/web-push-testing-service) something I found with a quick Google search.

**Comment by nikoksr** [comment]
> > > > @KaviiSuri @gedw99 does any of you happen to know an easy way for us to test this solution end-to-end? It's pretty safe to assume that [SherClockHolmes/webpush-go](https://github.com/SherClockHolmes/webpush-go/) does its job well and just works, but I don't like the idea of just releasing the solution without checking its behavior once.
> > > > @gedw99 great idea, we'll definitely include this!
> > > 
> > > 
> > > I test E2E locally using Caddy, MkCert for the Server. Gives you a https locally with custom domain name. [FiloSottile/mkcert](https://github.com/FiloSottile/mkcert)
> > > For the Wasm services worker i use go.app: [maxence-charriere/go-app](https://github.com/maxence-charriere/go-app)
> > > I think it would be a good idea to make a little demo in this repo one day when there is time.
> > > In CI, I can run caddy and mkcert, using a makefile as part of github workflows. It's the exact same makefile used on your laptop, just called as part of CI. I like this because i get full control and don't need any docker containers in CI so its fast.
> > > For CI of the GUI, thats hard. I use screen shots and Goldens. Its brutal but works. I don't have a framework yet i can recommend because i use GIO which has build in screen shotting. It runs on web, desktop and mobile. SO its makes cross devcie testing easier. BUT gio is not used by others.
> > > But the idea is to deploy the web app as a github page as part of CI, then you can tell it to screenshot and then you can test you got the right screen shot against your golden screenshot.
> > > Because the makefiles are 100% OS independent you can test for all Desktops and their browsers.
> > > Again i tres that CI browser testing is HARD and these are only suggestions.
> > > I would be happy to work on this with someone.
> > 
> > 
> > Wow, fascinating! Thanks for sharing all that knowledge with us. I wasn't aware of screenshot based browser testing and thus neither of golden.
> > I wonder how or if we could reduce the complexity of this. [Here's](https://github.com/GoogleChromeLabs/web-push-testing-service) something I found with a quick Google search.
> 
> @nikoksr
> 
> Looks pretty old and hacky.
> 
> I have used this:
> 
> [saucelabs.com/resources/blog/how-to-test-push-notifications-on-android-and-ios-in-real-device-cloud](https://saucelabs.com/resources/blog/how-to-test-push-notifications-on-android-and-ios-in-real-device-cloud)

Oh, definitely! My thought process was rather about taking this as a starting point and building a suitable solution on it, but Saucelabs already seems to be doing all that.

I would definitely welcome E2E tests for protocol centric services in the future and since we're slowly moving more and more services away from a third-party dependency based implementation towards [http service](https://github.com/nikoksr/notify/tree/main/service/http) based implementations E2E testing might become more viable even for platform centric services too.

**Comment by gedw99** [comment]
> 

Lets start a New Issue or Discussion about this ?

**Comment by nikoksr** [comment]
Sure! Would you like to open it?

**Review by nikoksr — APPROVED** [review]

**Pull request merged**
